# Generated by Django 2.2.6 on 2019-12-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDChipReader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardID', models.CharField(max_length=255)),
                ('authorised', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
